### PR TITLE
allow setting support valid until to handle unused entities generated checks

### PR DESCRIPTION
**Pull request by hgs30**
allow setting support valid until to handle unused entities generated checks for entities that used to have support_remove but are now validity times entities

### CODE REVIEW

**Comment by realityforge** [comment]
This probably does not make sense. I can walk through it on Friday if you want?

**Review by realityforge — CHANGES_REQUESTED** [review]
Talk friday about this

**Comment by jcosmo** [comment]
Glad you are also concerned about this one, I didn't like that we were starting to introduce awareness of Validity to domgen.

**Comment by jcosmo** [comment]
Will not merge

**Pull request closed without merging**
