### PR TITLE
Updates to support struct inheritance.

### PR DESCRIPTION
**Pull request by icaughley**

### CODE REVIEW

**Comment by icaughley** [comment]
I got a bit eager. Doesn't work yet.

**Comment by icaughley** [comment]
Works now.

**Comment by realityforge** [comment]
Looks good so far but off the top of my head there is still more work that needs to be done. The generated struct artifacts in the gwt facet will not yet work with inheritance (See ```java_struct.java.erb```, ```jso_struct.java.erb``` and ```struct.java.erb`` in the templates directory). These should be easy enough to update. I am also not sure what impact inheritable structs have on jaxb bindings or xml facet. There is also the xmi generator but not sure we care enough about that

**Comment by realityforge** [comment]
Closing this off as it seems unlikely it will be finished

**Pull request closed without merging**
